//go:build !ignore_autogenerated

// Copyright (c) 2024 Aiven, Helsinki, Finland. https://aiven.io/

// Code generated by controller-gen. DO NOT EDIT.

package autoscaleruserconfig

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerUserConfig) DeepCopyInto(out *AutoscalerUserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerUserConfig.
func (in *AutoscalerUserConfig) DeepCopy() *AutoscalerUserConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalerUserConfig)
	in.DeepCopyInto(out)
	return out
}
