// Code generated by user config generator. DO NOT EDIT.
// +kubebuilder:object:generate=true

package datadoguserconfig

// Datadog tag defined by user
type DatadogTags struct {
	// +kubebuilder:validation:MaxLength=1024
	// Optional tag explanation
	Comment *string `groups:"create,update" json:"comment,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=200
	// Tag format and usage are described here: https://docs.datadoghq.com/getting_started/tagging. Tags with prefix 'aiven-' are reserved for Aiven.
	Tag string `groups:"create,update" json:"tag"`
}
type DatadogUserConfig struct {
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9]{1,256}$`
	// Datadog API key
	DatadogApiKey string `groups:"create,update" json:"datadog_api_key"`

	// +kubebuilder:validation:MaxItems=32
	// Custom tags provided by user
	DatadogTags []*DatadogTags `groups:"create,update" json:"datadog_tags,omitempty"`

	// Disable consumer group metrics
	DisableConsumerStats *bool `groups:"create,update" json:"disable_consumer_stats,omitempty"`

	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	// Number of separate instances to fetch kafka consumer statistics with
	KafkaConsumerCheckInstances *int `groups:"create,update" json:"kafka_consumer_check_instances,omitempty"`

	// +kubebuilder:validation:Minimum=2
	// +kubebuilder:validation:Maximum=300
	// Number of seconds that datadog will wait to get consumer statistics from brokers
	KafkaConsumerStatsTimeout *int `groups:"create,update" json:"kafka_consumer_stats_timeout,omitempty"`

	// +kubebuilder:validation:Minimum=200
	// +kubebuilder:validation:Maximum=200000
	// Maximum number of partition contexts to send
	MaxPartitionContexts *int `groups:"create,update" json:"max_partition_contexts,omitempty"`

	// +kubebuilder:validation:Enum="datadoghq.com";"datadoghq.eu";"us3.datadoghq.com";"us5.datadoghq.com";"ddog-gov.com";"ap1.datadoghq.com"
	// Datadog intake site. Defaults to datadoghq.com
	Site *string `groups:"create,update" json:"site,omitempty"`
}
