// Code generated by user config generator. DO NOT EDIT.
// +kubebuilder:object:generate=true

package logsuserconfig

type LogsUserConfig struct {
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	// Elasticsearch index retention limit
	ElasticsearchIndexDaysMax *int `groups:"create,update" json:"elasticsearch_index_days_max,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=1024
	// +kubebuilder:validation:Pattern=`^[a-z0-9][a-z0-9-_.]+$`
	// Elasticsearch index prefix
	ElasticsearchIndexPrefix *string `groups:"create,update" json:"elasticsearch_index_prefix,omitempty"`

	// +kubebuilder:validation:MaxItems=5
	// The list of logging fields that will be sent to the integration logging service. The MESSAGE and timestamp fields are always sent.
	SelectedLogFields []string `groups:"create,update" json:"selected_log_fields,omitempty"`
}
