version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - testifylint
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    staticcheck:
      checks: ["all", "-QF1008"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - golint
          - gosec
        path: _test\.go
        text: underscore
      - linters:
          - mnd
        text: "Magic number: 0o644"
    paths:
      - api/v1alpha1/zz_generated.deepcopy.go
      - hack
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - api/v1alpha1/zz_generated.deepcopy.go
      - hack
      - third_party$
      - builtin$
      - examples$
