//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2022 Aiven, Helsinki, Finland. https://aiven.io/

// Code generated by controller-gen. DO NOT EDIT.

package kafkaconnectuserconfig

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConnect) DeepCopyInto(out *KafkaConnect) {
	*out = *in
	if in.ConfigStorageTopic != nil {
		in, out := &in.ConfigStorageTopic, &out.ConfigStorageTopic
		*out = new(string)
		**out = **in
	}
	if in.GroupId != nil {
		in, out := &in.GroupId, &out.GroupId
		*out = new(string)
		**out = **in
	}
	if in.OffsetStorageTopic != nil {
		in, out := &in.OffsetStorageTopic, &out.OffsetStorageTopic
		*out = new(string)
		**out = **in
	}
	if in.StatusStorageTopic != nil {
		in, out := &in.StatusStorageTopic, &out.StatusStorageTopic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConnect.
func (in *KafkaConnect) DeepCopy() *KafkaConnect {
	if in == nil {
		return nil
	}
	out := new(KafkaConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConnectUserConfig) DeepCopyInto(out *KafkaConnectUserConfig) {
	*out = *in
	if in.KafkaConnect != nil {
		in, out := &in.KafkaConnect, &out.KafkaConnect
		*out = new(KafkaConnect)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConnectUserConfig.
func (in *KafkaConnectUserConfig) DeepCopy() *KafkaConnectUserConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaConnectUserConfig)
	in.DeepCopyInto(out)
	return out
}
