// Code generated by user config generator. DO NOT EDIT.
// +kubebuilder:object:generate=true

package clickhousepostgresqluserconfig

// Database to expose
type Databases struct {
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// PostgreSQL database to expose
	Database *string `groups:"create,update" json:"database,omitempty"`

	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// PostgreSQL schema to expose
	Schema *string `groups:"create,update" json:"schema,omitempty"`
}

// Integration user config
type ClickhousePostgresqlUserConfig struct {
	// +kubebuilder:validation:MaxItems=10
	// Databases to expose
	Databases []*Databases `groups:"create,update" json:"databases,omitempty"`
}
