// Code generated by user config generator. DO NOT EDIT.
// +kubebuilder:object:generate=true

package externalgooglecloudlogginguserconfig

// User configuration for Google Cloud Logging integration
type ExternalGoogleCloudLoggingUserConfig struct {
	// +kubebuilder:validation:MaxLength=512
	// Google Cloud Logging log id
	LogId string `groups:"create,update" json:"log_id"`

	// +kubebuilder:validation:MinLength=6
	// +kubebuilder:validation:MaxLength=30
	// GCP project id.
	ProjectId string `groups:"create,update" json:"project_id"`

	// +kubebuilder:validation:MaxLength=4096
	// This is a JSON object with the fields documented in https://cloud.google.com/iam/docs/creating-managing-service-account-keys .
	ServiceAccountCredentials string `groups:"create,update" json:"service_account_credentials"`
}
