// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

const serviceUserRotationDefaultSecretPrefix = "SERVICEUSER_"

// ServiceUserRotationSpec defines the desired state of ServiceUserRotation.
// +kubebuilder:validation:XValidation:rule="size(self.connInfoSecretTarget.name) > 0",message="connInfoSecretTarget.name must not be empty."
// +kubebuilder:validation:XValidation:rule="self.connInfoSecretTarget.name == oldSelf.connInfoSecretTarget.name",message="connInfoSecretTarget.name is immutable."
// +kubebuilder:validation:XValidation:rule="(has(self.connInfoSecretTarget.prefix) && size(self.connInfoSecretTarget.prefix) > 0 ? self.connInfoSecretTarget.prefix : 'SERVICEUSER_') == (has(oldSelf.connInfoSecretTarget.prefix) && size(oldSelf.connInfoSecretTarget.prefix) > 0 ? oldSelf.connInfoSecretTarget.prefix : 'SERVICEUSER_')",message="connInfoSecretTarget.prefix is immutable."
type ServiceUserRotationSpec struct {
	ServiceDependant `json:",inline"`

	// Usernames is the ordered pool of Aiven service users managed by this resource.
	// The order determines the rotation sequence. The controller creates missing users and adopts matching existing users.
	// Unless the Orphan deletion policy is used, deleting this resource deletes every user in the pool.
	// +kubebuilder:validation:MinItems=2
	// +kubebuilder:validation:MaxItems=100
	// +kubebuilder:validation:items:MinLength=1
	// +kubebuilder:validation:items:MaxLength=64
	// +kubebuilder:validation:XValidation:rule="self.all(x, self.exists_one(y, y == x))",message="usernames must be unique."
	// +kubebuilder:validation:XValidation:rule="self.all(username, username != 'avnadmin')",message="avnadmin cannot be managed by ServiceUserRotation."
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="usernames is immutable."
	Usernames []string `json:"usernames"`

	// RotationInterval is the minimum time between scheduled credential rotations.
	// Measured from the publication time saved in the connection Secret; must be at least one minute.
	// +kubebuilder:validation:XValidation:rule="duration(self) >= duration('1m')",message="rotationInterval must be at least 1m."
	RotationInterval metav1.Duration `json:"rotationInterval"`

	// ConnInfoSecretTarget specifies the dedicated Kubernetes Secret that stores the active connection details
	// and credentials. The Secret is controlled by this resource and must not be shared.
	// A name is required; the name and effective key prefix are immutable. An empty prefix defaults to SERVICEUSER_.
	ConnInfoSecretTarget ConnInfoSecretTarget `json:"connInfoSecretTarget"`
}

// ServiceUserRotationStatus reports observations of the users and published connection Secret.
type ServiceUserRotationStatus struct {
	// Conditions represent the latest available observations of the resource's state.
	Conditions []metav1.Condition `json:"conditions"`

	// ActiveUsername is the Aiven service user whose credentials are currently published in the connection Secret.
	ActiveUsername string `json:"activeUsername,omitempty"`

	// LastRotationAt is the publication time recorded in the connection Secret, when the current rotation interval began.
	// Refreshing connection details does not reset it.
	LastRotationAt metav1.Time `json:"lastRotationAt,omitempty,omitzero"`

	// NextRotationAt is the scheduled time for the next credential rotation.
	NextRotationAt metav1.Time `json:"nextRotationAt,omitempty,omitzero"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// ServiceUserRotation manages an ordered pool of Aiven service users and publishes
// the active user's connection details and credentials through a stable Kubernetes Secret.
// Passwords are generated by the operator and sent to Aiven during rotation.
// The active user's password is not repaired if it changes or the user is recreated.
// See [Service user rotation](../guides/serviceuser-rotation.md) for lifecycle and limitations.
//
// Reading connection details also requires `service:secrets:read` for ServiceGet with `include_secrets=true`.
//
// Info "Exposes secret keys": `SERVICEUSER_HOST`, `SERVICEUSER_PORT`, `SERVICEUSER_USERNAME`, `SERVICEUSER_PASSWORD`, `SERVICEUSER_CA_CERT`, `SERVICEUSER_ACCESS_CERT`, `SERVICEUSER_ACCESS_KEY`, `SERVICEUSER_SASL_HOST`, `SERVICEUSER_SASL_PORT`, `SERVICEUSER_SCHEMA_REGISTRY_HOST`, `SERVICEUSER_SCHEMA_REGISTRY_PORT`
// +kubebuilder:printcolumn:name="Service Name",type="string",JSONPath=".spec.serviceName"
// +kubebuilder:printcolumn:name="Project",type="string",JSONPath=".spec.project"
// +kubebuilder:printcolumn:name="Active User",type="string",JSONPath=".status.activeUsername"
// +kubebuilder:printcolumn:name="Next Rotation",type="date",JSONPath=".status.nextRotationAt"
// +kubebuilder:printcolumn:name="Connection Information Secret",type="string",JSONPath=".spec.connInfoSecretTarget.name"
type ServiceUserRotation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServiceUserRotationSpec   `json:"spec,omitempty"`
	Status ServiceUserRotationStatus `json:"status,omitempty"`
}

var _ AivenManagedObject = &ServiceUserRotation{}

func (in *ServiceUserRotation) AuthSecretRef() *AuthSecretReference {
	return in.Spec.AuthSecretRef
}

func (in *ServiceUserRotation) Conditions() *[]metav1.Condition {
	return &in.Status.Conditions
}

func (in *ServiceUserRotation) GetObjectMeta() *metav1.ObjectMeta {
	return &in.ObjectMeta
}

func (*ServiceUserRotation) NoSecret() bool {
	return false
}

func (in *ServiceUserRotation) GetConnInfoSecretTarget() ConnInfoSecretTarget {
	target := in.Spec.ConnInfoSecretTarget
	if target.Prefix == "" {
		target.Prefix = serviceUserRotationDefaultSecretPrefix
	}
	return target
}

// +kubebuilder:object:root=true

// ServiceUserRotationList contains a list of ServiceUserRotation.
type ServiceUserRotationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceUserRotation `json:"items"`
}
