//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2024 Aiven, Helsinki, Finland. https://aiven.io/

// Code generated by controller-gen. DO NOT EDIT.

package jolokiauserconfig

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JolokiaUserConfig) DeepCopyInto(out *JolokiaUserConfig) {
	*out = *in
	if in.BasicAuthPassword != nil {
		in, out := &in.BasicAuthPassword, &out.BasicAuthPassword
		*out = new(string)
		**out = **in
	}
	if in.BasicAuthUsername != nil {
		in, out := &in.BasicAuthUsername, &out.BasicAuthUsername
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JolokiaUserConfig.
func (in *JolokiaUserConfig) DeepCopy() *JolokiaUserConfig {
	if in == nil {
		return nil
	}
	out := new(JolokiaUserConfig)
	in.DeepCopyInto(out)
	return out
}
