apiVersion: aiven.io/v1alpha1
kind: Database
metadata:
  name: my-db
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  serviceName: my-pg

  # Database name will default to the value of `metadata.name` if `databaseName` is not specified.
  # Use the `databaseName` field if the desired database name contains underscores.
  databaseName: my_db_name

  lcCtype: en_US.UTF-8
  lcCollate: en_US.UTF-8
