apiVersion: aiven.io/v1alpha1
kind: ServiceUser
metadata:
  name: my-service-user
spec:
  authSecretRef:
    name: aiven-token
    key: token

  connInfoSecretTarget:
    name: service-user-secret
    prefix: MY_SECRET_PREFIX_
    annotations:
      foo: bar
    labels:
      baz: egg

  # Optional: Use existing secret for credential management
  # connInfoSecretSource:
  #   name: predefined-credentials
  #   namespace: my-namespace  # Optional: defaults to same namespace as ServiceUser
  #   passwordKey: PASSWORD

  project: aiven-project-name
  serviceName: my-service-name
