apiVersion: aiven.io/v1alpha1
kind: ServiceIntegrationEndpoint
metadata:
  name: my-autoscaler
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  endpointType: autoscaler
  endpointName: my-autoscaler
  autoscaler:
    autoscaling:
      - type: autoscale_disk
        cap_gb: 100

---

apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  name: my-service-integration
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  integrationType: autoscaler
  sourceServiceName: my-pg
  destinationEndpointRef:
    name: my-autoscaler

---

apiVersion: aiven.io/v1alpha1
kind: PostgreSQL
metadata:
  name: my-pg
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  cloudName: google-europe-west1
  plan: startup-4
