//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright (c) 2022 Aiven, Helsinki, Finland. https://aiven.io/

// Code generated by controller-gen. DO NOT EDIT.

package datadoguserconfig

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogTags) DeepCopyInto(out *DatadogTags) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogTags.
func (in *DatadogTags) DeepCopy() *DatadogTags {
	if in == nil {
		return nil
	}
	out := new(DatadogTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogUserConfig) DeepCopyInto(out *DatadogUserConfig) {
	*out = *in
	if in.DatadogDbmEnabled != nil {
		in, out := &in.DatadogDbmEnabled, &out.DatadogDbmEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DatadogTags != nil {
		in, out := &in.DatadogTags, &out.DatadogTags
		*out = make([]*DatadogTags, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DatadogTags)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ExcludeConsumerGroups != nil {
		in, out := &in.ExcludeConsumerGroups, &out.ExcludeConsumerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeTopics != nil {
		in, out := &in.ExcludeTopics, &out.ExcludeTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeConsumerGroups != nil {
		in, out := &in.IncludeConsumerGroups, &out.IncludeConsumerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeTopics != nil {
		in, out := &in.IncludeTopics, &out.IncludeTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KafkaCustomMetrics != nil {
		in, out := &in.KafkaCustomMetrics, &out.KafkaCustomMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxJmxMetrics != nil {
		in, out := &in.MaxJmxMetrics, &out.MaxJmxMetrics
		*out = new(int)
		**out = **in
	}
	if in.Opensearch != nil {
		in, out := &in.Opensearch, &out.Opensearch
		*out = new(Opensearch)
		(*in).DeepCopyInto(*out)
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(Redis)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogUserConfig.
func (in *DatadogUserConfig) DeepCopy() *DatadogUserConfig {
	if in == nil {
		return nil
	}
	out := new(DatadogUserConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Opensearch) DeepCopyInto(out *Opensearch) {
	*out = *in
	if in.IndexStatsEnabled != nil {
		in, out := &in.IndexStatsEnabled, &out.IndexStatsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PendingTaskStatsEnabled != nil {
		in, out := &in.PendingTaskStatsEnabled, &out.PendingTaskStatsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PshardStatsEnabled != nil {
		in, out := &in.PshardStatsEnabled, &out.PshardStatsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Opensearch.
func (in *Opensearch) DeepCopy() *Opensearch {
	if in == nil {
		return nil
	}
	out := new(Opensearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redis) DeepCopyInto(out *Redis) {
	*out = *in
	if in.CommandStatsEnabled != nil {
		in, out := &in.CommandStatsEnabled, &out.CommandStatsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redis.
func (in *Redis) DeepCopy() *Redis {
	if in == nil {
		return nil
	}
	out := new(Redis)
	in.DeepCopyInto(out)
	return out
}
