// Code generated by user config generator. DO NOT EDIT.
// +kubebuilder:object:generate=true

package externalawscloudwatchmetricsuserconfig

// Metric name and subfield
type DroppedMetrics struct {
	// +kubebuilder:validation:MaxLength=1000
	// Identifier of a value in the metric
	Field string `groups:"create,update" json:"field"`

	// +kubebuilder:validation:MaxLength=1000
	// Identifier of the metric
	Metric string `groups:"create,update" json:"metric"`
}

// Metric name and subfield
type ExtraMetrics struct {
	// +kubebuilder:validation:MaxLength=1000
	// Identifier of a value in the metric
	Field string `groups:"create,update" json:"field"`

	// +kubebuilder:validation:MaxLength=1000
	// Identifier of the metric
	Metric string `groups:"create,update" json:"metric"`
}

// External AWS CloudWatch Metrics integration user config
type ExternalAwsCloudwatchMetricsUserConfig struct {
	// +kubebuilder:validation:MaxItems=1024
	// Metrics to not send to AWS CloudWatch (takes precedence over extra_metrics)
	DroppedMetrics []*DroppedMetrics `groups:"create,update" json:"dropped_metrics,omitempty"`

	// +kubebuilder:validation:MaxItems=1024
	// Metrics to allow through to AWS CloudWatch (in addition to default metrics)
	ExtraMetrics []*ExtraMetrics `groups:"create,update" json:"extra_metrics,omitempty"`
}
