apiVersion: aiven.io/v1alpha1
kind: ClickhouseRole
metadata:
  name: my-role
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: my-aiven-project
  serviceName: my-clickhouse
  role: my_role
