# This example demonstrates how to use ClickhouseUser with connInfoSecretSource
# for credential management. The ClickhouseUser will use a
# predefined password from an existing secret.

apiVersion: v1
kind: Secret
metadata:
  name: predefined-credentials
data:
  # MyCustomPassword123! base64 encoded
  PASSWORD: TXlDdXN0b21QYXNzd29yZDEyMyE= # gitleaks:allow

---

apiVersion: aiven.io/v1alpha1
kind: Clickhouse
metadata:
  name: my-clickhouse
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  cloudName: google-europe-west1
  plan: startup-16

  connInfoSecretTarget:
    name: clickhouse-connection
    prefix: CH_
    annotations:
      example: clickhouse-service
    labels:
      service: clickhouse

---

apiVersion: aiven.io/v1alpha1
kind: ClickhouseUser
metadata:
  name: my-clickhouse-user
spec:
  authSecretRef:
    name: aiven-token
    key: token

  connInfoSecretTarget:
    name: clickhouse-user-secret
    prefix: MY_CLICKHOUSE_PREFIX_
    annotations:
      foo: bar
    labels:
      baz: egg

  # Use existing secret for credential management
  connInfoSecretSource:
    name: predefined-credentials
    # namespace: my-namespace  # Optional: defaults to same namespace as ClickhouseUser
    passwordKey: PASSWORD

  project: aiven-project-name
  serviceName: my-clickhouse
  username: example-username