apiVersion: aiven.io/v1alpha1
kind: Project
metadata:
  name: my-project
spec:
  authSecretRef:
    name: aiven-token
    key: token

  tags:
    env: prod

  accountId: my-account-id
  billingAddress: NYC
  cloud: aws-eu-west-1
