apiVersion: aiven.io/v1alpha1
kind: ServiceIntegrationEndpoint
metadata:
  name: my-service-integration-endpoint
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  endpointName: my-autoscaler
  endpointType: autoscaler

  autoscaler:
    autoscaling:
      - type: autoscale_disk
        cap_gb: 100
