# This example demonstrates how to use ServiceUser with connInfoSecretSource
# for credential management. The ServiceUser will use a
# predefined password from an existing secret.

apiVersion: v1
kind: Secret
metadata:
  name: predefined-credentials
data:
  # MySecurePassword123! base64 encoded
  PASSWORD: TXlTZWN1cmVQYXNzd29yZDEyMyE= # gitleaks:allow

---

apiVersion: aiven.io/v1alpha1
kind: PostgreSQL
metadata:
  name: my-postgresql
spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name
  cloudName: google-europe-west1
  plan: startup-4

  connInfoSecretTarget:
    name: postgresql-connection
    prefix: PG_
    annotations:
      example: postgresql-service
    labels:
      service: postgresql

---

apiVersion: aiven.io/v1alpha1
kind: ServiceUser
metadata:
  name: my-service-user
spec:
  authSecretRef:
    name: aiven-token
    key: token

  connInfoSecretTarget:
    name: service-user-secret
    prefix: MY_SECRET_PREFIX_
    annotations:
      foo: bar
    labels:
      baz: egg

  # Use existing secret for credential management
  connInfoSecretSource:
    name: predefined-credentials
    # namespace: my-namespace  # Optional: defaults to same namespace as ServiceUser
    passwordKey: PASSWORD

  project: aiven-project-name
  serviceName: my-postgresql