name: generate files

on:
  pull_request: {}

permissions:
  actions: read
  checks: write
  contents: write
  security-events: write
  statuses: write

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto_commit.outputs.commit_hash }}
      changes_detected: ${{ steps.auto_commit.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
      - run: curl https://get.trunk.io -fsSL | bash
      - name: generate files
        run: make generate
      - id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(userconfigs): generate files"

  run_lint:
    needs: generate
    if: needs.generate.outputs.changes_detected == 'true'
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ needs.generate.outputs.commit_hash }}

  report_statuses:
    needs: [generate, run_lint]
    if: always() && needs.generate.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .github/actions
      - uses: ./.github/actions/report-statuses
        with:
          sha: ${{ needs.generate.outputs.commit_hash }}
          statuses: >-
            {
              "generate": "success",
              "commitlint": "${{ needs.run_lint.outputs.commitlint }}",
              "lint-go": "${{ needs.run_lint.outputs.lint-go }}",
              "trunk": "${{ needs.run_lint.outputs.trunk }}",
              "codeql_analysis": "${{ needs.run_lint.outputs.codeql_analysis }}",
              "kustomize_can_build_deployment": "${{ needs.run_lint.outputs.kustomize_can_build_deployment }}"
            }
